version: "3"
services:
  frontend:
    container_name: frontend
    build:
      context: ./Front
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    restart: always
  server:
    container_name: server
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9999:9999"
    restart: always
