version: "3"
services:
  frontend:
    container_name: frontend
    build:
      context: ./Front
      dockerfile: Dockerfile
    volumes:
      - ./nginx/dist/:/app/dist
    ports:
      - "5173:5173"
  server:
    container_name: server
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9999:9999"
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/dist/:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - frontend
      - server
    command: /bin/bash -c "nginx -g 'daemon off;'"
