version: "3"
services:
  frontend:
    container_name: frontend
    build:
      context: ./Front
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    restart: always
  server:
    container_name: server
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9999:9999"
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
