version: '3'
services:
  neighbrew:
    container_name: neighbrew
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    restart: always
    environment:
      - NODE_ENV=production
    # Add any other environment variables if required
