package com.ssafy.backend.Enum;

public enum PushType {
    LOSTDATA,
    COMMNET, COMMNETLIKE,
    FOLLOW,
    CHAT,
    MEETACCESS, MEETREJECT, MEETEVALUATION, MEETCREATED, MEETMODIFIDE, MEETDELETED
}
